module.exports.GLOBAL_MISSING_REQUIRED_PARAMETER_ERROR_CODE = 'ERR_1000'
module.exports.GLOBAL_WRONG_MAIL_FORMAT_ERROR_CODE = 'ERR_1001'

module.exports.USER_INVALID_CREDENTIALS_ERROR_CODE = 'ERR_2000'