module.exports.GLOBAL_MISSING_REQUIRED_PARAMETER_ERROR_CODE = 'ERR_1000'
module.exports.GLOBAL_WRONG_MAIL_FORMAT_ERROR_CODE = 'ERR_1001'
module.exports.GLOBAL_NOT_ALLOWED_CHARACTER_ERROR_CODE = 'ERR_1002'

module.exports.USER_NOT_ALLOWED_ERROR_CODE = 'ERR_2000'
module.exports.USER_INVALID_CREDENTIALS_ERROR_CODE = 'ERR_2001'
module.exports.USER_MAIL_ALREADY_USED_ERROR_CODE = 'ERR_2002'