# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.8.0
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
      # CircleCI PostgreSQL images available at: https://hub.docker.com/r/circleci/postgres/
      - image: circleci/postgres:12-alpine
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          PGUSER: circleci
          POSTGRES_USER: circleci
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: password 
          POSTGRES_HOST_AUTH_METHOD: trust

    steps:
      - checkout
      - run: node --version
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client-12
      - run:
          name: Wait for db to run
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 1m
      - run: |
          psql \
          -h 127.0.0.1 \
          -d $MHLM_TEST_DB_NAME \
          -U circleci \
          -c "CREATE TABLE test (name char(25));"
    
workflows:
  test:
    jobs:
      - build
