# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.8.0
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
      # CircleCI PostgreSQL images available at: https://hub.docker.com/r/circleci/postgres/
      - image: circleci/postgres:12-alpine
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          PGUSER: ${MHLM_TEST_DB_USERNAME} # Must be set to "circleci"
          POSTGRES_USER: ${MHLM_TEST_DB_USERNAME} # Must be set to "circleci"
          POSTGRES_DB: ${MHLM_TEST_DB_NAME} # Must be set to "circle_test"
          POSTGRES_PASSWORD: ${MHLM_TEST_DB_PASSWORD}
          POSTGRES_HOST_AUTH_METHOD: trust

    steps:
      - checkout
      - run: 
          name: Install PostgreSQL Client
          command: sudo apt-get update && sudo apt-get install postgresql-client-12
      - run:
          name: Wait for db to run
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 1m
      - run: 
          name: Test to create a table
          command: |
            psql \
            -h 127.0.0.1 \
            -d circle_test \
            -U circleci \
            -c "CREATE TABLE test (name char(25));"

      - run: 
          name: Check Sequelieze config
          command: cat .sequelizerc

      - run: 
          name: Install App dependencies
          command: npm install

      - run: 
          name: Tests API
          command: |
            npm run test

    
workflows:
  test:
    jobs:
      - build
