# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1

jobs:
  build:
    docker:
      # CircleCI PostgreSQL images available at: https://hub.docker.com/r/circleci/postgres/
      - image: circleci/postgres:10-alpine
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
        environment:
          POSTGRES_DB: $MHLM_TEST_DB_NAME
          POSTGRES_USER: $MHLM_TEST_DB_USERNAME
          POSTGRES_PASSWORD: $MHLM_TEST_DB_PASSWORD

    steps:
      - run: apt-get update
      - run: apt-get install postgresql-client-10
      - run: whoami
      - run: |
          psql \
          -d $POSTGRES_DB \
          -c "CREATE TABLE test (name char(25));"

workflows:
  test:
    jobs:
      - build
      - node/test:
          version: '15.1'
          # This is the node version to use for the `cimg/node` tag
          # Relevant tags can be found on the CircleCI Developer Hub
          # https://circleci.com/developer/images/image/cimg/node
